version: '3.1'

services:
  crediplus_api:
    build:
      context: ./BackEnd
    image: mcr.microsoft.com/dotnet/samples:aspnetapp
    container_name: test_api_crediplus
    restart: always
    ports:
      - 7070:80
    environment:
      - TZ=America/Bogota
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  crediplus_front:
    build:
      context: ./FrontEnd
    container_name: test_front_crediplus
    restart: always
    ports:
      - 7073:80

  crediplus_usuarios:
    build:
      context: ./Usuarios
    container_name: test_usuarios_crediplus
    restart: always
    ports:
      - 7079:80
