version: '3.1'

services:
  crediplus_api_pruebas:
    build:
      context: ./BackEnd
    image: mcr.microsoft.com/dotnet/samples:aspnetapp
    container_name: crediplus_api_pruebas
    restart: always
    ports:
      - 8070:80
    environment:
      - TZ=America/Bogota
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  crediplus_test_admin:
    build:
      context: ./FrontEnd
    container_name: crediplus_test_admin
    restart: always
    ports:
      - 8073:80

  crediplus_test_usuarios:
    build:
      context: ./Usuarios
    container_name: crediplus_test_usuarios
    restart: always
    ports:
      - 8079:80
