services:
  crediplus_api_pruebas:
    build:
      context: ./BackEnd
    image: mcr.microsoft.com/dotnet/samples:aspnetapp
    container_name: crediplus_api_pruebas
    restart: always
    ports:
      - 8070:80
    environment:
      - TZ=America/Bogota
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80